### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Blomquist10** [MartijnvanGeffen13/Volvo4evcc#36]
Installed all acc your advice and all went fine. but when start your moule i got this:
![2024-12-22 15_22_48](https://github.com/user-attachments/assets/b322f79a-9d43-4b58-af6b-296dccd5cdb4)
All pathes seems right:
![image](https://github.com/user-attachments/assets/62840462-6685-4283-be69-8dd107ebf604)
what is wrong, canyou help

**Comment by MartijnvanGeffen13** [comment]
> Installed all acc your advice and all went fine. but when start your moule i got this: ![2024-12-22 15_22_48](https://private-user-images.githubusercontent.com/93371678/397991648-b322f79a-9d43-4b58-af6b-296dccd5cdb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODQwNTIsIm5iZiI6MTczNDg4Mzc1MiwicGF0aCI6Ii85MzM3MTY3OC8zOTc5OTE2NDgtYjMyMmY3OWEtOWQ0My00YjU4LWFmNmItMjk2ZGNjZDVjZGI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE2MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzhjMzMzNDEyMDE4ZGVkNTZjNGIxZTQ3ODMxMGRlMzFmZWQyYzNhYTA1MzdjYTg5ZGQyNTVjYjlkNWY3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUvurSp-avYLYc2YHANFibuz7E73jVn4czZ1z-KGC1s) All pathes seems right: ![image](https://private-user-images.githubusercontent.com/93371678/397991752-62840462-6685-4283-be69-8dd107ebf604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODQwNTIsIm5iZiI6MTczNDg4Mzc1MiwicGF0aCI6Ii85MzM3MTY3OC8zOTc5OTE3NTItNjI4NDA0NjItNjY4NS00MjgzLWJlNjktOGRkMTA3ZWJmNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE2MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MWVkMjJiM2Q1MTRkMjBhN2JlNzg1N2VjOTQ4YTAwMzY0MTEwNmI0ZTFjNzAyM2UzNDViZmJlMTZmNWUyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fhFVEaAYi-nE9lh1TkGQbb660HisGEWFzGf3fUKiSpo) what is wrong, canyou help

Looks like you missed the prerequisit for the dns module.

If on linux host execute:

PWSH Install-Module "DnsClient-PS"

Than you should be able to start the module

**Comment by Blomquist10** [comment]
Hi Martijn,

works so far:



Puted your adapted yaml in the evcc.yaml



 

 

But when i start evcc application i get first this message:

Fehler beim Starten. Überprüfe deine Konfiguration und starte neu.

While parsing config: yaml: line 53: did not find expected '-' indicator

 

And when i move `- name…` to the left i get this:

 



 

Fehler beim Starten. Überprüfe deine Konfiguration und starte neu.

While parsing config: yaml: line 55: mapping values are not allowed in this context

 

Please, can you help one more time?

 

Mit freundlichem Gruß

Best regards

 

Gerd Kötter

 

Von: Martijn (Scriptkiddie) van Geffen ***@***.***> 
Gesendet: Sonntag, 22. Dezember 2024 17:13
An: MartijnvanGeffen13/Volvo4evcc ***@***.***>
Cc: Blomquist10 ***@***.***>; Author ***@***.***>
Betreff: Re: [MartijnvanGeffen13/Volvo4evcc] Need help (Issue #36)

 

Installed all acc your advice and all went fine. but when start your moule i got this: All pathes seems right: what is wrong, canyou help

Looks like you missed the prerequisit for the dns module.

If on linux host execute:

PWSH Install-Module "DnsClient-PS"

Than you should be able to start the module

**Comment by MartijnvanGeffen13** [comment]
sure, 

Can you post the relevant part of the Yaml code here how you have it atm.

**Comment by Blomquist10** [comment]
You mean this file

 

Mit freundlichem Gruß

Best regards

 

Gerd Kötter

 

Von: Martijn (Scriptkiddie) van Geffen ***@***.***> 
Gesendet: Sonntag, 22. Dezember 2024 21:34
An: MartijnvanGeffen13/Volvo4evcc ***@***.***>
Cc: Blomquist10 ***@***.***>; Author ***@***.***>
Betreff: Re: [MartijnvanGeffen13/Volvo4evcc] Need help (Issue #36)

 

sure,

Can you post the relevant part of the Yaml code here how you have it atm.

**Comment by MartijnvanGeffen13** [comment]
Note if you reply via mail the images dont load , 

I see your post but not the content

**Comment by Blomquist10** [comment]
Thank's Martijn, this is my christmas gift from you, i'm really happy
![image](https://github.com/user-attachments/assets/9d76f2d5-6c4e-412c-b03a-a5230c0c15c7)

**Comment by MartijnvanGeffen13** [comment]
Good to hear,  and enjoy.

You might also want to check out the integrated weather module, its described in the wiki. I am running with it for weeks now must say its pretty good. Hardly have to touch the solar / snell buttons anymore

**Comment by MartijnvanGeffen13** [comment]
Closing this issue as resolved

**Comment by MartijnvanGeffen13** [comment]
[heart]         Martijn van Geffen reacted to your message:
________________________________
